monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%/debug.log"
                level: debug
                channels: ["!event"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            dump:
                type: fingers_crossed
                action_level: error
                handler: file_log
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            file_log:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%/error_dump.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/debug.log"
                level: debug
                filename_format: '{date}--{filename}'
                max_files: 1
            dump:
                type: fingers_crossed
                action_level: critical
                handler: file_log
            file_log:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%/critical_dump.log"
                filename_format: '{date}--{filename}'
                max_files: 31
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: rotating_file
                channels: [deprecation]
                path: "%kernel.logs_dir%/%kernel.environment%/deprecation.log"
                filename_format: '{date}--{filename}'
                max_files: 1
            syslog_handler:
                type: syslog
                level: error
