cas:
    base_url: '%env(CAS_HOST)%:%env(CAS_PORT)%%env(CAS_PATH)%'
    protocol:
        login:
            path: /login
            allowed_parameters:
                - service
                - renew
                - gateway
            default_parameters:
                service: '%env(CAS_LOGIN_TARGET)%'
        serviceValidate:
            path: /p3/serviceValidate
            allowed_parameters:
                - service
                - pgtUrl
                - renew
                - format
            default_parameters:
                format: JSON
                #pgtUrl: cas_bundle_proxy_callback
        logout:
            path: /logout
            allowed_parameters:
                - service
            default_parameters:
                service: '%env(CAS_LOGOUT_TARGET)%'
        proxy:
            path: /proxy
            allowed_parameters:
                - targetService
                - pgt
        proxyValidate:
            path: /p3/proxyValidate
            allowed_parameters:
                - service
                - ticket
                - pgtUrl
                - format
            default_parameters:
                format: JSON
                #pgtUrl: cas_bundle_proxy_callback
