controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

ajax_get_courses:
    path: /get-courses
    controller: App\Controller\CourseController::getCoursesAction
    methods: [GET]

ajax_get_assignees:
    path: /get-assignees
    controller: App\Controller\AssigneeController::getAssigneesAction
    methods: [GET]

ajax_get_institutions:
    path: /get-institutions
    controller: App\Controller\InstitutionController::getInstitutionsAction
    methods: [GET]
